[project]
name = 'School-Air-Quality-Transparency'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.community-dashboard-and-grants]
path = 'contracts/community-dashboard-and-grants.clar'
clarity_version = 3
epoch = 'latest'

[contracts.exposure-notifications]
path = 'contracts/exposure-notifications.clar'
clarity_version = 3
epoch = '3.2'

[contracts.iaq-sensor-network]
path = 'contracts/iaq-sensor-network.clar'
clarity_version = 3
epoch = '3.2'

[contracts.ventilation-optimization]
path = 'contracts/ventilation-optimization.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
